# Generated by Django 2.1.7 on 2019-03-16 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='device',
            new_name='owner',
        ),
    ]
